<a href="https://colab.research.google.com/github/pranukrish/CMPE297-SpecialTopics/blob/main/Assignment1/MNIST_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [4]:
# Load the MNIST dataset
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [5]:
# Normalize the pixel values to be between 0 and 1
x_train = x_train / 255.0
x_test = x_test / 255.0

In [6]:
# Define the model architecture
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(10, activation='softmax')
])

In [7]:
# Compile the model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [8]:
# Train the model
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2948 - accuracy: 0.9143
Epoch 2/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1416 - accuracy: 0.9573
Epoch 3/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1067 - accuracy: 0.9683
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0877 - accuracy: 0.9732
Epoch 5/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0753 - accuracy: 0.9763
Epoch 6/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0660 - accuracy: 0.9788
Epoch 7/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0592 - accuracy: 0.9812
Epoch 8/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0520 - accuracy: 0.9836
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0480 - accuracy: 0.9840
Epoch 10/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.044

In [9]:
# Evaluate the model on the test set
test_loss, test_acc = model.evaluate(x_test, y_test)
print('Test accuracy:', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0752 - accuracy: 0.9792
Test accuracy: 0.979200005531311


In [10]:
# Make predictions on some example inputs
example_inputs = x_test[:5]
example_labels = y_test[:5]
example_predictions = model.predict(example_inputs)
example_predictions = np.argmax(example_predictions, axis=1)

1/1 [==============================] - 0s 55ms/step


In [11]:
# Print the example inputs, labels, and predictions
print('Example inputs:')
print(example_inputs)
print('Example labels:')
print(example_labels)
print('Example predictions:')
print(example_predictions)

Example inputs:
[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
Example labels:
[7 2 1 0 4]
Example predictions:
[7 2 1 0 4]
